// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCOfEz1Ov3ai36ifDRH9Y8X9uYHPJ1BpS8',
//     appId: '1:886619458553:web:8b8bccb7d887f3aa67cb28',
//     messagingSenderId: '886619458553',
//     projectId: 'kafela-ebc05',
//     authDomain: 'kafela-ebc05.firebaseapp.com',
//     storageBucket: 'kafela-ebc05.firebasestorage.app',
//     measurementId: 'G-TVPGFZR8YN',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBQu2TthMSEQYHFiO4RZ64NBFBS3pAvr2I',
//     appId: '1:886619458553:android:2a28cc50ac6740af67cb28',
//     messagingSenderId: '886619458553',
//     projectId: 'kafela-ebc05',
//     storageBucket: 'kafela-ebc05.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDGhMvedSXhTECjkkFuqolDOpq5tmtqg5o',
//     appId: '1:886619458553:ios:4744a3028689d0bb67cb28',
//     messagingSenderId: '886619458553',
//     projectId: 'kafela-ebc05',
//     storageBucket: 'kafela-ebc05.firebasestorage.app',
//     iosBundleId: 'com.example.kafela',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDGhMvedSXhTECjkkFuqolDOpq5tmtqg5o',
//     appId: '1:886619458553:ios:4744a3028689d0bb67cb28',
//     messagingSenderId: '886619458553',
//     projectId: 'kafela-ebc05',
//     storageBucket: 'kafela-ebc05.firebasestorage.app',
//     iosBundleId: 'com.example.kafela',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCOfEz1Ov3ai36ifDRH9Y8X9uYHPJ1BpS8',
//     appId: '1:886619458553:web:e8e9275e9fd5d8c267cb28',
//     messagingSenderId: '886619458553',
//     projectId: 'kafela-ebc05',
//     authDomain: 'kafela-ebc05.firebaseapp.com',
//     storageBucket: 'kafela-ebc05.firebasestorage.app',
//     measurementId: 'G-JL9NR28P40',
//   );
// }
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOfEz1Ov3ai36ifDRH9Y8X9uYHPJ1BpS8',
    appId: '1:886619458553:web:8b8bccb7d887f3aa67cb28',
    messagingSenderId: '886619458553',
    projectId: 'kafela-ebc05',
    authDomain: 'kafela-ebc05.firebaseapp.com',
    storageBucket: 'kafela-ebc05.firebasestorage.app',
    measurementId: 'G-TVPGFZR8YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQu2TthMSEQYHFiO4RZ64NBFBS3pAvr2I',
    appId: '1:886619458553:android:2a28cc50ac6740af67cb28',
    messagingSenderId: '886619458553',
    projectId: 'kafela-ebc05',
    storageBucket: 'kafela-ebc05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGhMvedSXhTECjkkFuqolDOpq5tmtqg5o',
    appId: '1:886619458553:ios:4744a3028689d0bb67cb28',
    messagingSenderId: '886619458553',
    projectId: 'kafela-ebc05',
    storageBucket: 'kafela-ebc05.firebasestorage.app',
    iosBundleId: 'com.example.kafela',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGhMvedSXhTECjkkFuqolDOpq5tmtqg5o',
    appId: '1:886619458553:ios:4744a3028689d0bb67cb28',
    messagingSenderId: '886619458553',
    projectId: 'kafela-ebc05',
    storageBucket: 'kafela-ebc05.firebasestorage.app',
    iosBundleId: 'com.example.kafela',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOfEz1Ov3ai36ifDRH9Y8X9uYHPJ1BpS8',
    appId: '1:886619458553:web:e8e9275e9fd5d8c267cb28',
    messagingSenderId: '886619458553',
    projectId: 'kafela-ebc05',
    authDomain: 'kafela-ebc05.firebaseapp.com',
    storageBucket: 'kafela-ebc05.firebasestorage.app',
    measurementId: 'G-JL9NR28P40',
  );
}